<2020-09-16 18:11:50.743896> [Join] The bot has connected to vivivi
<2020-09-16 18:12:48.189437> [Leave] The bot has disconnected to vivivi in 라응애
<2020-09-16 18:12:50.295825> [Join] The bot has connected to vivivi
<2020-09-16 18:12:50.983944> [Queue] Have queue
<2020-09-16 18:12:50.984017> [Queue] First message
<2020-09-16 18:12:51.250770> [Queue] Have queue
<2020-09-16 18:12:51.250828> [Queue] After message
<2020-09-16 18:12:52.094638> [Leave] The bot has disconnected to vivivi in 라응애
<2020-09-16 18:14:14.598228> [Join] The bot has connected to vivivi
<2020-09-16 18:14:23.525553> [Queue] Have queue
<2020-09-16 18:14:23.525757> [Queue] First message
<2020-09-16 18:14:29.339046> [Leave] The bot has disconnected to vivivi in 라응애
<2020-09-16 18:18:22.192756> [Join] The bot has connected to vivivi
<2020-09-16 18:18:27.411196> [Leave] The bot has disconnected to vivivi in 라응애
<2020-09-16 18:18:34.806616> [Queue] Have queue
<2020-09-16 18:18:34.806720> [Queue] First message
<2020-09-16 18:39:08.619899> [Queue] Have queue
<2020-09-16 18:39:08.619970> [Queue] First message
<2020-09-16 18:39:17.190478> [Queue] Have queue
<2020-09-16 18:39:17.190603> [Queue] After message
<2020-09-16 18:41:54.382276> [on_command_error] Command raised an exception: OperationalError: database is locked
<2020-09-16 18:43:56.005604> [Join] The bot has connected to vivivi
<2020-09-16 18:44:20.910890> [Join] The bot has connected to vivivi
<2020-09-16 18:44:26.386820> [on_command_error] Command "뷁" is not found
<2020-09-16 18:44:41.283893> [Join] This bot is already in vivivi
<2020-09-16 18:44:41.584101> [Queue] Have queue
<2020-09-16 18:44:41.584156> [Queue] First message
<2020-09-16 18:44:41.877456> [Queue] Have queue
<2020-09-16 18:44:41.877502> [Queue] After message
<2020-09-16 18:44:42.644139> [on_command_error] Command raised an exception: ValueError: too many values to unpack (expected 2)
<2020-09-16 18:45:58.252356> [Join] The bot has connected to vivivi
<2020-09-16 18:46:40.258136> [Join] The bot has connected to vivivi
<2020-09-16 18:47:04.506523> [Join] The bot has connected to vivivi
<2020-09-16 18:47:06.334744> [Leave] The bot has disconnected to vivivi in 라응애
<2020-09-16 21:58:28.693549> [Join] The bot has connected to 일반
<2020-09-16 21:59:10.697350> [Join] The bot has connected to 일반
<2020-09-16 22:15:36.140123> [on_command_error] Command raised an exception: UnboundLocalError: local variable 'log_message' referenced before assignment
<2020-09-16 22:16:34.484447> [on_command_error] Command raised an exception: NameError: name 'server_name' is not defined
<2020-09-16 22:17:06.299265> [Search] First message
<2020-09-16 22:17:06.576399> [Search] Searched []
<2020-09-16 22:17:37.853258> [Search] First message
<2020-09-16 22:17:38.156352> [Search] Searched []
<2020-09-16 22:17:47.908882> [Search] After message
<2020-09-16 22:17:48.169469> [Search] Searched [망상감상]
<2020-09-16 22:18:29.836536> [Search] There is no searching words
<2020-09-16 22:18:29.836561> [Search] After message
<2020-09-16 22:18:40.789955> [Search] There is no searching words
<2020-09-16 22:18:41.040457> [Search] After message
<2020-09-16 22:18:47.147033> [Search] After message
<2020-09-16 22:18:47.419878> [Search] Searched [망상감상]
<2020-09-19 00:03:24.308990> [Join] The bot has connected to 일반
<2020-09-19 00:03:32.161043> [on_command_error] Command raised an exception: TypeError: 'tuple' object does not support item assignment
<2020-09-19 00:04:21.424221> [Search] There is no searching words
<2020-09-19 00:04:21.424258> [Search] After message
<2020-09-19 00:04:28.515046> [Join] The bot has connected to 일반
<2020-09-19 00:04:30.752501> [on_command_error] Command raised an exception: TypeError: 'tuple' object does not support item assignment
<2020-09-19 00:05:29.641341> [Join] The bot has connected to 일반
<2020-09-19 00:05:31.241826> [Join] This bot is already in 일반
<2020-09-19 00:05:37.000057> [Search] First message
<2020-09-19 00:05:37.314276> [Search] Searched [망상감상]
<2020-09-19 00:56:07.584575> [Join] The bot has connected to 일반
<2020-09-19 00:56:10.648137> [on_command_error] Command raised an exception: NameError: name 'search_set' is not defined
<2020-09-19 00:56:44.860822> [Join] The bot has connected to 일반
<2020-09-19 00:56:49.332876> [on_command_error] Command raised an exception: TypeError: object of type 'generator' has no len()
<2020-09-19 00:57:26.386855> [Join] The bot has connected to 일반
<2020-09-19 00:57:28.839801> [on_command_error] Command "망상감상" is not found
<2020-09-19 00:57:36.567505> [Join] This bot is already in 일반
<2020-09-19 00:57:42.363519> [on_command_error] Command raised an exception: TypeError: object of type 'generator' has no len()
<2020-09-19 00:58:37.103526> [Join] The bot has connected to 일반
<2020-09-19 00:58:40.055312> [Search] First message
<2020-09-19 00:58:40.338505> [Search] Searched [망상감상]
<2020-09-19 01:03:26.695901> [Queue] Have queue
<2020-09-19 01:03:26.696013> [Queue] First message
<2020-09-19 01:11:23.822630> [Join] The bot has connected to 일반
<2020-09-19 01:11:28.427872> [Search] First message
<2020-09-19 01:11:28.735868> [Search] Searched [망상감상]
<2020-09-19 01:12:05.237228> [Search] First message
<2020-09-19 01:12:05.509365> [Search] Searched [안녕]
<2020-09-19 01:12:29.341673> [Search] First message
<2020-09-19 01:12:29.638556> [Search] Searched [안녕]
<2020-09-19 01:21:25.393827> [on_command_error] Command raised an exception: ValueError: Invalid duration value: PT3M46S
<2020-09-19 01:24:45.847165> [on_command_error] Command raised an exception: ValueError: Invalid isoformat string: 'PT3M46S'
<2020-09-19 01:44:22.303532> [on_command_error] Command raised an exception: KeyError: 'videoId'
<2020-09-19 01:45:15.420918> [Search] First message
<2020-09-19 01:45:15.700993> [Search] Searched [6시간 이어듣기]
<2020-09-19 01:45:44.468766> [Search] After message
<2020-09-19 01:45:44.786193> [Search] Searched [24시간동안 라이더하기?]
<2020-09-19 01:46:18.856457> [Search] First message
<2020-09-19 01:46:19.150912> [Search] Searched [24시간동안 라이더하기?]
<2020-09-19 02:01:49.500798> [on_command_error] Command raised an exception: NameError: name 'parse_iso8601' is not defined
<2020-09-19 02:03:02.227571> [Search] First message
<2020-09-19 02:03:02.562820> [Search] Searched [24시간동안 라이더하기?]
<2020-09-19 02:03:26.976197> [Search] First message
<2020-09-19 02:03:27.334592> [Search] Searched [24시간동안 라이더하기?]
<2020-09-19 02:04:37.657151> [Search] First message
<2020-09-19 02:04:38.008440> [Search] Searched [24시간동안 라이더하기?]
<2020-09-19 02:05:57.698690> [Search] First message
<2020-09-19 02:05:58.001044> [Search] Searched [24시간동안 라이더하기?]
<2020-09-19 02:06:18.613767> [Search] First message
<2020-09-19 02:06:18.935295> [Search] Searched [24시간동안 라이더하기?]
<2020-09-19 02:09:23.435809> [Search] First message
<2020-09-19 02:09:23.765162> [Search] Searched [망상감상대상연맹]
<2020-09-19 02:09:30.520008> [on_command_error] Command raised an exception: OperationalError: near ")": syntax error
<2020-09-19 02:10:33.254684> [Search] First message
<2020-09-19 02:10:33.565877> [Search] Searched [망상감상대상연맹]
<2020-09-19 02:10:38.154013> [on_command_error] Command raised an exception: OperationalError: table Queues has no column named Duration
<2020-09-19 02:11:29.909627> [Join] The bot has connected to 일반
<2020-09-19 02:11:44.757750> [Search] First message
<2020-09-19 02:11:45.082685> [Search] Searched [망상감상]
<2020-09-19 02:11:47.510270> [on_command_error] Command raised an exception: InterfaceError: Error binding parameter 5 - probably unsupported type.
<2020-09-19 02:12:19.455234> [Search] First message
<2020-09-19 02:12:19.784879> [Search] Searched [망상감ㅅ아]
<2020-09-19 02:12:22.520162> [on_command_error] Command raised an exception: InterfaceError: Error binding parameter 5 - probably unsupported type.
<2020-09-19 02:12:41.056172> [Join] The bot has connected to 일반
<2020-09-19 02:12:46.591119> [on_command_error] Command raised an exception: InterfaceError: Error binding parameter 5 - probably unsupported type.
<2020-09-19 02:14:11.252177> [Join] The bot has connected to 일반
<2020-09-19 02:14:14.640515> [Search] First message
<2020-09-19 02:14:14.906128> [Search] Searched [망상감상]
<2020-09-19 02:14:17.119933> [on_command_error] Command raised an exception: InterfaceError: Error binding parameter 5 - probably unsupported type.
<2020-09-19 02:16:03.433879> [Search] First message
<2020-09-19 02:16:03.736452> [Search] Searched [망상감상]
<2020-09-19 02:16:05.451400> [on_command_error] Command raised an exception: InterfaceError: Error binding parameter 5 - probably unsupported type.
<2020-09-19 02:16:59.936539> [Join] The bot has connected to 일반
<2020-09-19 02:17:03.230169> [Search] First message
<2020-09-19 02:17:03.523589> [Search] Searched [망상감상]
<2020-09-19 02:17:04.588616> [on_command_error] Command raised an exception: InterfaceError: Error binding parameter 5 - probably unsupported type.
<2020-09-19 02:17:47.564540> [Search] First message
<2020-09-19 02:17:47.839826> [Search] Searched [망상감ㅅ아]
<2020-09-19 02:17:49.545057> [on_command_error] Command raised an exception: OperationalError: no such table: Queues
<2020-09-19 02:18:49.457300> [Join] The bot has connected to 일반
<2020-09-19 02:19:00.404655> [on_command_error] Command raised an exception: InterfaceError: Error binding parameter 5 - probably unsupported type.
<2020-09-19 02:20:31.168728> [Search] First message
<2020-09-19 02:20:31.523390> [Search] Searched [망상]
<2020-09-19 02:26:48.692017> [Search] There is no searching words
<2020-09-19 02:26:48.692053> [Search] After message
<2020-09-19 02:26:52.466592> [Search] After message
<2020-09-19 02:26:52.774306> [Search] Searched [망상감ㅅ다]
<2020-09-19 02:27:28.893384> [Search] First message
<2020-09-19 02:27:29.168319> [Search] Searched [망상감상]
<2020-09-19 02:28:40.645609> [Join] The bot has connected to 일반
